In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("nav.csv")
df.head()

                                      Scheme Name  Net Asset Value       Date
0  quant Active Fund-GROWTH OPTION - Regular Plan         185.5863  01-Jan-20
1  quant Active Fund-GROWTH OPTION - Regular Plan         187.5911  02-Jan-20
2  quant Active Fund-GROWTH OPTION - Regular Plan         187.2149  03-Jan-20
3  quant Active Fund-GROWTH OPTION - Regular Plan         183.0497  06-Jan-20
4  quant Active Fund-GROWTH OPTION - Regular Plan         184.5715  07-Jan-20

In [3]:
df.size

244281

In [4]:
def remove_regular_plans(df):
    df_filtered = df[~df['Scheme Name'].str.contains('Regular Plan')]
    
    return df_filtered

df_filtered = remove_regular_plans(df)
df_filtered.head()

                                      Scheme Name  Net Asset Value       Date
1064  quant Active Fund-GROWTH OPTION-Direct Plan         188.2185  01-Jan-20
1065  quant Active Fund-GROWTH OPTION-Direct Plan         190.2523  02-Jan-20
1066  quant Active Fund-GROWTH OPTION-Direct Plan         189.8713  03-Jan-20
1067  quant Active Fund-GROWTH OPTION-Direct Plan         185.6485  06-Jan-20
1068  quant Active Fund-GROWTH OPTION-Direct Plan         187.1924  07-Jan-20

In [5]:
df_filtered.size

139224

In [6]:
def remove_IDCW_Option(df):
    df_filtered = df[~df['Scheme Name'].str.contains('IDCW')]
    
    return df_filtered

df_filtered = remove_IDCW_Option(df_filtered)
df_filtered.head()

                                      Scheme Name  Net Asset Value       Date
1064  quant Active Fund-GROWTH OPTION-Direct Plan         188.2185  01-Jan-20
1065  quant Active Fund-GROWTH OPTION-Direct Plan         190.2523  02-Jan-20
1066  quant Active Fund-GROWTH OPTION-Direct Plan         189.8713  03-Jan-20
1067  quant Active Fund-GROWTH OPTION-Direct Plan         185.6485  06-Jan-20
1068  quant Active Fund-GROWTH OPTION-Direct Plan         187.1924  07-Jan-20

In [7]:
df_filtered.size

81165

In [8]:
print(df_filtered)

                                            Scheme Name  Net Asset Value  \
1064        quant Active Fund-GROWTH OPTION-Direct Plan         188.2185
1065        quant Active Fund-GROWTH OPTION-Direct Plan         190.2523
1066        quant Active Fund-GROWTH OPTION-Direct Plan         189.8713
1067        quant Active Fund-GROWTH OPTION-Direct Plan         185.6485
1068        quant Active Fund-GROWTH OPTION-Direct Plan         187.1924
...                                                 ...              ...
79294  quant Flexi Cap Fund - Growth Option-Direct Plan         105.7456
79295  quant Flexi Cap Fund - Growth Option-Direct Plan         105.6542
79296  quant Flexi Cap Fund - Growth Option-Direct Plan         105.4820
79297  quant Flexi Cap Fund - Growth Option-Direct Plan         106.3012
79298  quant Flexi Cap Fund - Growth Option-Direct Plan         106.6306

            Date
1064   01-Jan-20
1065   02-Jan-20
1066   03-Jan-20
1067   06-Jan-20
1068   07-Jan-20
...          ...
79294  16-Apr-24
79295  18-Apr-24
79296  19-Apr-24
79297  22-Apr-24
79298  23-Apr-24

[27055 rows x 3 columns]

In [9]:
def mean_nav_on_day_of_month(df, fund_name, day_of_month):
    # Convert 'Date' column to datetime
    df['Date'] = pd.to_datetime(df['Date'], format='%d-%b-%y')
    
    # Filter rows for the specified fund
    fund_df = df[df['Scheme Name'].str.contains(fund_name)]
    
    # Filter rows for the specified day of the month
    day_df = fund_df[fund_df['Date'].dt.day == day_of_month]
    
    # Calculate mean NAV
    mean_nav = day_df['Net Asset Value'].mean()
    
    return mean_nav

In [10]:
mean_nav = mean_nav_on_day_of_month(df_filtered, 'quant Flexi Cap Fund - Growth Option-Direct Plan', 4)
mean_nav

57.43903823529412

In [11]:
def mean_nav_per_day_of_month(df, fund_name):
    # Convert 'Date' column to datetime
    df['Date'] = pd.to_datetime(df['Date'], format='%d-%b-%y')
    
    # Filter rows for the specified fund
    fund_df = df[df['Scheme Name'].str.contains(fund_name)]
    
    # Create a new DataFrame to store mean NAV for each day of the month
    days_of_month = range(1, 32)  # Assuming maximum 31 days in a month
    mean_nav_data = {'Day': [], 'Mean NAV': []}
    
    for day in days_of_month:
        day_df = fund_df[fund_df['Date'].dt.day == day]
        mean_nav = day_df['Net Asset Value'].mean()
        mean_nav_data['Day'].append(day)
        mean_nav_data['Mean NAV'].append(mean_nav)
    
    # Create DataFrame from the mean NAV data
    mean_nav_df = pd.DataFrame(mean_nav_data)
    
    return mean_nav_df

In [12]:
# result_df = mean_nav_for_all_days(df_filtered, 'quant Flexi Cap Fund - Growth Option-Direct Plan')
fund_name = 'quant Flexi Cap Fund - Growth Option-Direct Plan'
mean_nav_per_day = mean_nav_per_day_of_month(df, fund_name)

In [13]:
mean_nav_per_day

    Day   Mean NAV
0     1  58.815175
1     2  58.196164
2     3  54.555108
3     4  57.439038
4     5  59.210524
5     6  57.869025
6     7  56.712578
7     8  57.636157
8     9  56.928914
9    10  56.938506
10   11  57.255768
11   12  59.562344
12   13  57.006344
13   14  57.764839
14   15  58.456109
15   16  57.696453
16   17  53.722700
17   18  58.094080
18   19  59.073336
19   20  56.726116
20   21  58.454923
21   22  58.107826
22   23  56.747232
23   24  52.384241
24   25  55.739410
25   26  56.929707
26   27  56.229792
27   28  56.961930
28   29  57.384391
29   30  54.976560
30   31  58.812224

In [14]:
min(mean_nav_per_day['Mean NAV'])

52.384241176470596

In [15]:
def day_with_lowest_mean_nav(mean_nav_df):
    # Find the row with the lowest mean NAV
    min_nav_row = mean_nav_df.loc[mean_nav_df['Mean NAV'].idxmin()]
    
    # Extract the day with the lowest mean NAV
    day_with_lowest_nav = min_nav_row['Day']
    
    return day_with_lowest_nav

In [16]:
day_with_lowest_nav = day_with_lowest_mean_nav(mean_nav_per_day)
day_with_lowest_nav

24.0

In [17]:
def lowest_mean_nav_day_month(df):
    # Convert 'Date' column to datetime
    df['Date'] = pd.to_datetime(df['Date'], format='%d-%b-%y')
    
    # Create a new DataFrame to store lowest mean NAV details
    lowest_nav_data = {'Scheme Name': [], 'Day': [], 'Month': [], 'Mean NAV': []}
    
    # Get unique scheme names
    unique_schemes = df['Scheme Name'].unique()
    
    # Loop through each unique scheme
    for scheme in unique_schemes:
        # Filter rows for the current scheme
        scheme_df = df[df['Scheme Name'] == scheme]
        
        # Calculate mean NAV for each day of the month
        mean_nav_per_day = scheme_df.groupby(df['Date'].dt.day)['Net Asset Value'].mean().reset_index()
        
        # Find the day with the lowest mean NAV
        min_nav_row = mean_nav_per_day.loc[mean_nav_per_day['Net Asset Value'].idxmin()]
        
        # Extract day, month, and mean NAV
        day_with_lowest_nav = min_nav_row['Date']
        month_with_lowest_nav = df[df['Date'].dt.day == day_with_lowest_nav]['Date'].iloc[0].month
        lowest_mean_nav = min_nav_row['Net Asset Value']
        
        # Append data to lowest_nav_data
        lowest_nav_data['Scheme Name'].append(scheme)
        lowest_nav_data['Day'].append(day_with_lowest_nav)
        lowest_nav_data['Month'].append(month_with_lowest_nav)
        lowest_nav_data['Mean NAV'].append(lowest_mean_nav)
    
    # Create DataFrame from lowest NAV data
    lowest_nav_df = pd.DataFrame(lowest_nav_data)
    
    return lowest_nav_df

In [18]:
lowest_nav_day_month_df = lowest_mean_nav_day_month(df_filtered)

In [19]:
lowest_nav_day_month_df

                                          Scheme Name   Day  Month    Mean NAV
0         quant Active Fund-GROWTH OPTION-Direct Plan  24.0      1  367.495735
1   quant Large Cap Fund - Growth Option - Direct ...  24.0      1   10.469491
2   quant Large & Mid Cap Fund - Bonus Option-Dire...  24.0      1   59.708188
3          quant Large & Mid Cap Fund - Growth Option  24.0      1   59.677032
4   quant Large & Mid Cap Fund - Growth Option-Dir...  24.0      1   62.300594
5    quant Mid Cap Fund - Growth Option - Direct Plan  24.0      1  112.437197
6   quant Small Cap Fund - Growth Option - Direct ...  24.0      1  114.984709
7     Quant Value Fund - Growth Option  - Direct Plan  24.0      1   11.478665
8      quant Focused Fund - Growth Option-Direct Plan  24.0      1   50.306803
9       quant BFSI Fund - Growth Option - Direct Plan  25.0      2   12.023820
10  quant Business Cycle Fund - Growth Option - Di...  25.0      2   12.201340
11  quant Commodities Fund - Growth Option - Direc...  17.0      1   10.041300
12  quant Consumption Fund - Growth Option - Direc...  30.0      1    9.994900
13  quant ESG Equity Fund - Growth Option - Direct...  24.0      1   19.512200
14  quant Healthcare Fund - Growth Option - Direct...  25.0      2   10.918220
15          quant Infrastructure Fund - Growth Option  24.0      1   17.325291
16  quant Infrastructure Fund - Growth Option-Dire...  24.0      1   18.222318
17  quant Manufacturing Fund - Growth Option - Dir...  25.0      2   11.160750
18  quant Momentum Fund - Growth Option - Direct Plan  24.0      1   11.096750
19       quant PSU Fund - Growth Option - Direct Plan  13.0      1    9.459800
20  quant Quantamental Fund - Growth Option - Dire...  24.0      1   13.244132
21      quant Teck Fund - Growth Option - Direct Plan  25.0      2   10.400067
22  quant ELSS Tax Saver Fund - Growth Option - Di...  24.0      1  201.331668
23  quant Overnight Fund - Growth Option - Direct ...  24.0      1   10.411673
24    quant Liquid Fund - Growth Option - Direct Plan  24.0      1   34.237963
25  quant Liquid Fund-Unclaimed Dividend Investor ...  24.0      1   10.832556
26  quant Liquid Fund-Unclaimed Dividend-Growth Op...  24.0      1   10.833038
27  quant Liquid Fund-Unclaimed Redemption Investo...  24.0      1   10.832550
28  quant Liquid Fund-Unclaimed Redemption Plan-Gr...  24.0      1   10.842797
29            Quant Money Market Fund-Dividend Option   6.0      1   16.929256
30  Quant Money Market Fund-Dividend Option-Direct...   6.0      1   16.949900
31              Quant Money Market Fund-Growth Option   6.0      1   31.414778
32  Quant Money Market Fund-Growth Option-Direct Plan   6.0      1   31.695522
33                           Quant Dynamic Bond-Bonus  13.0      1   33.122520
34        Quant Dynamic Bond-Bonus Option-Direct Plan  13.0      1   33.122520
35                        Quant Dynamic Bond-Dividend  13.0      1   11.987410
36     Quant Dynamic Bond-Dividend Option-Direct Plan  13.0      1   12.192110
37                          Quant Dynamic Bond-Growth  13.0      1   62.977630
38       Quant Dynamic Bond-Growth Option-Direct Plan  13.0      1   63.870430
39      quant Gilt Fund - Growth Option - Direct Plan  24.0      1   10.379267
40      quant Absolute Fund-Growth Option-Direct Plan  24.0      1  250.968282
41  quant Dynamic Asset Allocation Fund - Growth O...  25.0      2   11.367300
42   quant Multi Asset Fund-GROWTH OPTION-Direct Plan  24.0      1   70.183147
43   quant Flexi Cap Fund - Growth Option-Direct Plan  24.0      1   52.384241

In [20]:
lowest_nav_day_month_df['Day'].median()

24.0

In [21]:
def highest_mean_nav_day_month(df):
    # Convert 'Date' column to datetime
    df['Date'] = pd.to_datetime(df['Date'], format='%d-%b-%y')
    
    # Create a new DataFrame to store highest mean NAV details
    highest_nav_data = {'Scheme Name': [], 'Day': [], 'Month': [], 'Mean NAV': []}
    
    # Get unique scheme names
    unique_schemes = df['Scheme Name'].unique()
    
    # Loop through each unique scheme
    for scheme in unique_schemes:
        # Filter rows for the current scheme
        scheme_df = df[df['Scheme Name'] == scheme]
        
        # Calculate mean NAV for each day of the month
        mean_nav_per_day = scheme_df.groupby(df['Date'].dt.day)['Net Asset Value'].mean().reset_index()
        
        # Find the day with the highest mean NAV
        max_nav_row = mean_nav_per_day.loc[mean_nav_per_day['Net Asset Value'].idxmax()]
        
        # Extract day, month, and mean NAV
        day_with_highest_nav = max_nav_row['Date']
        month_with_highest_nav = df[df['Date'].dt.day == day_with_highest_nav]['Date'].iloc[0].month
        highest_mean_nav = max_nav_row['Net Asset Value']
        
        # Append data to highest_nav_data
        highest_nav_data['Scheme Name'].append(scheme)
        highest_nav_data['Day'].append(day_with_highest_nav)
        highest_nav_data['Month'].append(month_with_highest_nav)
        highest_nav_data['Mean NAV'].append(highest_mean_nav)
    
    # Create DataFrame from highest NAV data
    highest_nav_df = pd.DataFrame(highest_nav_data)
    
    return highest_nav_df

In [22]:
highest_nav_day_month_df = highest_mean_nav_day_month(df_filtered)

In [23]:
highest_nav_day_month_df

                                          Scheme Name   Day  Month    Mean NAV
0         quant Active Fund-GROWTH OPTION-Direct Plan  12.0      2  413.229994
1   quant Large Cap Fund - Growth Option - Direct ...  15.0      1   11.683471
2   quant Large & Mid Cap Fund - Bonus Option-Dire...  12.0      2   66.885011
3          quant Large & Mid Cap Fund - Growth Option  12.0      2   66.835503
4   quant Large & Mid Cap Fund - Growth Option-Dir...  12.0      2   70.185106
5    quant Mid Cap Fund - Growth Option - Direct Plan  12.0      2  129.396956
6   quant Small Cap Fund - Growth Option - Direct ...  12.0      2  134.312056
7     Quant Value Fund - Growth Option  - Direct Plan   5.0      2   13.259868
8      quant Focused Fund - Growth Option-Direct Plan  12.0      2   56.255461
9       quant BFSI Fund - Growth Option - Direct Plan  15.0      1   14.219514
10  quant Business Cycle Fund - Growth Option - Di...  15.0      1   13.742725
11  quant Commodities Fund - Growth Option - Direc...   7.0      1   11.741150
12  quant Consumption Fund - Growth Option - Direc...   4.0      2   10.675500
13  quant ESG Equity Fund - Growth Option - Direct...   5.0      2   21.726748
14  quant Healthcare Fund - Growth Option - Direct...   5.0      2   12.471100
15          quant Infrastructure Fund - Growth Option  12.0      2   20.126433
16  quant Infrastructure Fund - Growth Option-Dire...  12.0      2   21.286244
17  quant Manufacturing Fund - Growth Option - Dir...  19.0      2   13.068433
18  quant Momentum Fund - Growth Option - Direct Plan  16.0      1   13.074900
19       quant PSU Fund - Growth Option - Direct Plan  10.0      1   10.492600
20  quant Quantamental Fund - Growth Option - Dire...  19.0      2   15.327591
21      quant Teck Fund - Growth Option - Direct Plan  19.0      2   11.510950
22  quant ELSS Tax Saver Fund - Growth Option - Di...  12.0      2  229.694483
23  quant Overnight Fund - Growth Option - Direct ...   4.0      2   10.532931
24    quant Liquid Fund - Growth Option - Direct Plan  19.0      2   34.634577
25  quant Liquid Fund-Unclaimed Dividend Investor ...  19.0      2   11.001417
26  quant Liquid Fund-Unclaimed Dividend-Growth Op...  19.0      2   11.001883
27  quant Liquid Fund-Unclaimed Redemption Investo...  19.0      2   11.001417
28  quant Liquid Fund-Unclaimed Redemption Plan-Gr...  19.0      2   11.015283
29            Quant Money Market Fund-Dividend Option  25.0      2   17.056583
30  Quant Money Market Fund-Dividend Option-Direct...  25.0      2   17.080333
31              Quant Money Market Fund-Growth Option  25.0      2   31.650917
32  Quant Money Market Fund-Growth Option-Direct Plan  25.0      2   31.938517
33                           Quant Dynamic Bond-Bonus  25.0      2   33.398483
34        Quant Dynamic Bond-Bonus Option-Direct Plan  25.0      2   33.398483
35                        Quant Dynamic Bond-Dividend  25.0      2   12.087283
36     Quant Dynamic Bond-Dividend Option-Direct Plan  25.0      2   12.295917
37                          Quant Dynamic Bond-Growth  25.0      2   63.502233
38       Quant Dynamic Bond-Growth Option-Direct Plan  25.0      2   64.414417
39      quant Gilt Fund - Growth Option - Direct Plan  15.0      1   10.588582
40      quant Absolute Fund-Growth Option-Direct Plan  12.0      2  277.802297
41  quant Dynamic Asset Allocation Fund - Growth O...  15.0      1   13.084233
42   quant Multi Asset Fund-GROWTH OPTION-Direct Plan  12.0      2   78.205706
43   quant Flexi Cap Fund - Growth Option-Direct Plan  12.0      2   59.562344

In [24]:
mahindra_df = pd.read_csv("mahindra_nav.csv")
df.head()

                                      Scheme Name  Net Asset Value       Date
0  quant Active Fund-GROWTH OPTION - Regular Plan         185.5863 2020-01-01
1  quant Active Fund-GROWTH OPTION - Regular Plan         187.5911 2020-01-02
2  quant Active Fund-GROWTH OPTION - Regular Plan         187.2149 2020-01-03
3  quant Active Fund-GROWTH OPTION - Regular Plan         183.0497 2020-01-06
4  quant Active Fund-GROWTH OPTION - Regular Plan         184.5715 2020-01-07

In [25]:
mahindra_df_filtered = remove_regular_plans(mahindra_df)
mahindra_df_filtered = remove_IDCW_Option(mahindra_df_filtered)
mahindra_df_filtered

,Scheme Name,Net Asset Value,Date
1709,Mahindra Manulife Multi Cap Fund - Direct Plan...,10.0138,18-May-17
1710,Mahindra Manulife Multi Cap Fund - Direct Plan...,10.0241,19-May-17
1711,Mahindra Manulife Multi Cap Fund - Direct Plan...,10.0454,22-May-17
1712,Mahindra Manulife Multi Cap Fund - Direct Plan...,10.0375,23-May-17
1713,Mahindra Manulife Multi Cap Fund - Direct Plan...,10.0318,24-May-17
...,...,...,...
119253,Mahindra Manulife Flexi Cap Fund - Direct Plan...,14.9408,16-Apr-24
119254,Mahindra Manulife Flexi Cap Fund - Direct Plan...,14.8839,18-Apr-24
119255,Mahindra Manulife Flexi Cap Fund - Direct Plan...,14.9327,19-Apr-24
119256,Mahindra Manulife Flexi Cap Fund - Direct Plan...,15.0870,22-Apr-24
119257,Mahindra Manulife Flexi Cap Fund - Direct Plan...,15.1649,23-Apr-24

In [26]:
lowest_nav_day_month_df = lowest_mean_nav_day_month(mahindra_df_filtered)
lowest_nav_day_month_df

,Scheme Name,Day,Month,Mean NAV
0,Mahindra Manulife Multi Cap Fund - Direct Plan...,24.0,5,16.266845
1,Mahindra Manulife Large Cap Fund - Direct Plan...,24.0,5,13.865080
2,Mahindra Manulife Large & Mid Cap Fund - Direc...,24.0,5,15.241129
3,Mahindra Manulife Mid Cap Fund - Direct Plan -...,24.0,5,14.292802
4,Mahindra Manulife Small Cap Fund - Direct Plan...,24.0,5,11.886411
5,Mahindra Manulife Focused Fund - Direct Plan -...,24.0,5,15.576635
6,Mahindra Manulife Business Cycle Fund - Direct...,25.0,5,10.511900
7,Mahindra Manulife Consumption Fund - Direct Pl...,24.0,5,12.865098
8,Mahindra Manulife ELSS Tax Saver Fund - Direct...,24.0,5,15.420477
9,Mahindra Manulife Overnight Fund - Direct Plan...,30.0,5,1099.565948
10,Mahindra Manulife Liquid Fund - Direct Plan -G...,5.0,6,1283.626173
11,Mahindra Manulife Ultra Short Duration Fund - ...,24.0,5,1116.377525
12,Mahindra Manulife Low Duration Fund - Direct P...,16.0,6,1277.032018
13,Mahindra Manulife Short Duration Fund - Direct...,25.0,5,10.731225
14,Mahindra Manulife Dynamic Bond Fund - Direct P...,24.0,5,11.756050
15,Mahindra Manulife Aggressive Hybrid Fund - Dir...,24.0,5,15.333058
16,Mahindra Manulife Balanced Advantage Fund - Di...,24.0,5,10.535131
17,Mahindra Manulife Multi Asset Allocation Fund-...,20.0,6,10.025400
18,Mahindra Manulife Arbitrage Fund - Direct Plan...,25.0,5,10.686043
19,Mahindra Manulife Equity Savings Fund - Direct...,24.0,5,14.053630
20,Mahindra Manulife Equity Savings Fund -Direct ...,26.0,5,12.618572
21,Mahindra Manulife Asia Pacific REITs FOF - Dir...,19.0,5,8.740033
22,Mahindra Manulife Flexi Cap Fund - Direct Plan...,24.0,5,10.836358

In [27]:
fund_name = 'Mahindra Manulife Multi Cap Fund - Direct Plan -Growth'
m_mean_nav_per_day = mean_nav_per_day_of_month(mahindra_df_filtered, fund_name)
m_mean_nav_per_day

    Day   Mean NAV
0     1  17.727618
1     2  17.881704
2     3  16.907632
3     4  17.125616
4     5  17.257256
5     6  17.174915
6     7  17.162012
7     8  17.545189
8     9  17.180233
9    10  17.349560
10   11  16.999744
11   12  17.602905
12   13  17.264346
13   14  17.007684
14   15  17.656257
15   16  17.355912
16   17  16.907105
17   18  17.214907
18   19  17.138946
19   20  17.284657
20   21  17.522164
21   22  17.394945
22   23  17.192807
23   24  16.266845
24   25  16.804759
25   26  16.559966
26   27  16.872707
27   28  17.220724
28   29  17.231047
29   30  16.558118
30   31  17.014424

In [28]:
min(m_mean_nav_per_day['Mean NAV'])

16.266845454545454

In [29]:
lowest_nav_day_month_df['Day'].median()

24.0

In [30]:
lowest_nav_day_month_df['Scheme Name'][6]

'Mahindra Manulife Business Cycle Fund - Direct Plan - Growth'